name: Publish to Artifact Registry

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish NPM Package
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Fetch all tags
      run: |
        git fetch --tags --force

    - name: Get Latest Tag
      id: get_new_tag
      run: |
        LATEST_TAG=$(git tag --sort=-creatordate | head -n 1)
        echo "LATEST_TAG=${LATEST_TAG}"
        echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
    
    - name: Validate Major/Minor Tag
      id: validate_tag
      run: |
        TAG="${{ env.LATEST_TAG }}"
        if [[ ! "$TAG" =~ ^[0-9]+\.[0-9]+\.0$ ]]; then
          echo "Invalid tag format. Expected format is X.Y.0 (e.g., 1.10.0)."
          exit 1
        fi

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_JSON_AUTH }}

    # Configurar NPM para Artifact Registry
    - name: Configure NPM for Artifact Registry
      run: |
        TOKEN=$(gcloud auth print-access-token)
        echo "//us-central1-npm.pkg.dev/pch-main/pch-npm-private/:_authToken=${TOKEN}" > ~/.npmrc
        echo "@pch-private:registry=https://us-central1-npm.pkg.dev/pch-main/pch-npm-private/" >> ~/.npmrc
        echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

    # Instalar dependencias
    - name: Install dependencies
      run: npm install

    # Compilar el paquete
    - name: Build Package
      run: npm run build

    # Actualizar la versión del paquete
    - name: Bump package version to latest tag
      run: |
        npm version ${TAG} --no-git-tag-version

    - name: Publish Artifact Registry
      run: |
        npm publish --registry=https://us-central1-npm.pkg.dev/pch-main/pch-npm-private/
